### ISSUE TITLE
Merge formatting changes + beep

### ISSUE THREAD

**Issue by Iaotle** [NickVeld/IND-Appointment-Check#7]
I changed the formatting of the script slightly to make it a bit easier to use. It's on my branch and it's a frankenstein because it's really hot outside and I'm feeling very lazy.

I also made it beep in terminal when a new appointment is found.

**Comment by NickVeld** [comment]
I have noticed that you have just copied our changes to your repository and it is considered as a theft in the open-source. world

Instead it is right to merge our `master` branch with yours. It can be done like this (you do not need any confirmation from me for it):

![image](https://user-images.githubusercontent.com/17028401/189114817-b3cd0947-034e-4549-9fe4-f8e65f2b9fe6.png)

![image](https://user-images.githubusercontent.com/17028401/189114957-e710c22b-844f-42e6-aa38-ec93c0e95893.png)

![image](https://user-images.githubusercontent.com/17028401/189115147-a3120618-eaa1-4afb-88ce-a209944c0674.png)

**Comment by NickVeld** [comment]
If you want to be a good guy, not a bad one then I recommend to the following create a branch with name "main" from the past commit:

![image](https://user-images.githubusercontent.com/17028401/189120898-11eb0a4a-41c1-43de-b735-35fa62341717.png)

Right-click on this commit:
![image](https://user-images.githubusercontent.com/17028401/189121231-1899b36f-07e8-4cf0-8aed-47fdaa551274.png)

![image](https://user-images.githubusercontent.com/17028401/189121320-bc922a91-a985-417d-8edf-c138eaa19011.png)

Type "main" (it is a default name for new repos) as a name of the new branch.

------

Then make this new branch as a default one: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

------
Finally open a pull request as in the previous my comment. But merge NickVeld/master into laotle/main. Then you need to reproduce the changes in your original "master" branch. And then merge the branch made by mitul45

(Maybe I will merge your and mitul45 's changes to help you if it is enough time)

**Comment by Iaotle** [comment]
I don't really have time to merge everything right now, I did credit you and license allows me to take your changes and merge them into mine anyway. I didn't know about the functionality to merge from other repos without a pr and I didn't want to spend a lot of time figuring it out. In future you are welcome to submit a pr and I will merge any changes you want to make :)

**Comment by Iaotle** [comment]
Also they are not exactly the same anymore and there's probably merge conflicts anyway. If you feel like messing around I could give you repo access as contrib.

**Comment by NickVeld** [comment]
> I didn't know about the functionality to merge from other repos without a pr

It is not without a PR, it is with a PR you can create.

> Also they are not exactly the same anymore and there's probably merge conflicts anyway. If you feel like messing around I could give you repo access as contrib.

I suppose I can overcome the conflicts. So the access would be appreciated.

**Comment by Iaotle** [comment]
@NickVeld added you

**Comment by NickVeld** [comment]
Thanks!

**Comment by NickVeld** [comment]
I have synchronized some your changes with `master` in my fork.

I have not transferred the changes for
* auto-cleaning the console (I do not know the profit but someone will lose console content printed before the app)
* "beeping" ( `print('\a')` is a thing that must be checked on all systems before placing it for every system; upd: it is not working in PyCharm console for example)
* adding time part to date comparison, instead I have added `earliest_time` in the place it is only required
* `, end='\r'` (What is the purpose? Such unpredictable invisible symbols can cause some troubles for an user)

If you wanted this changes anyway, could you please open a separate PR and I can comment lines and provide my thoughts

Now, I am going to check the changes from mitul45

**Comment by NickVeld** [comment]
Done: https://github.com/Iaotle/IND-Appointment-Check/pull/3 https://github.com/Iaotle/IND-Appointment-Check/pull/4

But I have no access to the settings so I cannot change the default branch. So, @Iaotle, could you please change the default branch from `master` to `main`: : https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by NickVeld** [comment]
> I don't really have time to merge everything right now

By the way you can just make PR in this repo as well in future.

**Comment by Iaotle** [comment]
Done.
